# Init

In [16]:
import sys
sys.path.append('../src')

from environments import LineEnv, GridEnv, MazeEnv
from policies import HardCodedAgent

import numpy as np

# Grid

In [17]:
env = GridEnv()
agent = HardCodedAgent(env)
value_function = agent.evaluate_policy()
print("Value Function:", value_function)

Value Function: [  0.          -7.55860372 -10.48587627 -11.38377519  -7.55860372
  -9.59194855 -10.53696679 -10.49293913 -10.48587627 -10.53696679
  -9.59779382  -7.56791637 -11.38377519 -10.49293913  -7.56791637
   0.        ]


In [18]:
env = GridEnv()
agent = HardCodedAgent(env)
agent.value_iteration()

print("Optimal Value Function:", agent.value_function)
print("Optimal Policy:", agent.policy)


Optimal Value Function: [ 0.     -1.     -1.95   -2.8525 -1.     -1.95   -2.8525 -1.95   -1.95
 -2.8525 -1.95   -1.     -2.8525 -1.95   -1.      0.    ]
Optimal Policy: [0 3 3 0 2 2 0 0 2 0 0 0 1 1 1 0]


# Maze

In [19]:
env = MazeEnv()
agent = HardCodedAgent(env)
value_function = agent.evaluate_policy()
print("Value Function:", value_function)

Value Function: [-19.84451684 -19.84797093 -19.8358753  -19.81300568 -19.84451684
 -19.84991095 -19.85765667 -19.86142441 -19.86113988 -19.77332157
 -19.79465002 -19.83874683 -19.54551498 -19.68580448 -19.81913187
 -19.78571999 -19.69024604 -19.55054228 -19.33529083 -19.82570494
 -18.78086734 -17.98410983 -16.77466618 -19.85084734 -19.85661
 -19.85318447 -19.86272239 -14.89529963 -19.86142319 -19.8680819
 -19.87048932  -7.30822042 -11.94776379 -19.86358875   0.        ]


In [20]:
env = MazeEnv()
agent = HardCodedAgent(env, gamma=1)
agent.value_iteration()

print("Optimal Value Function:", agent.value_function)
print("Optimal Policy:", agent.policy)


Optimal Value Function: [-14. -13. -12. -11. -14. -13. -14. -15. -14. -10. -11. -12.  -8.  -9.
 -11. -10.  -9.  -8.  -7. -11.  -6.  -5.  -4. -14. -13. -12. -13.  -3.
 -14. -14. -15.  -1.  -2. -15.   0.]
Optimal Policy: [0 1 1 0 1 0 3 1 2 0 3 0 0 3 1 1 1 1 0 2 1 1 0 1 1 2 3 0 2 2 3 0 3 2 0]


In [21]:
v = np.zeros((8, 8))
for i, (x, y) in env._state_to_grid.items():
    v[8-y-1, x] =  agent.value_function[i]

In [22]:
print(v)

[[  0. -15.   0.   0.   0.   0.   0.   0.]
 [  0. -14.   0. -14. -15.   0.  -1.  -2.]
 [-14. -13. -12. -13.   0.   0.   0.  -3.]
 [  0.   0. -11.   0.   0.  -6.  -5.  -4.]
 [  0. -11. -10.  -9.  -8.  -7.   0.   0.]
 [  0. -12.   0.   0.   0.  -8.  -9.   0.]
 [-14. -13. -14. -15. -14.   0. -10. -11.]
 [  0. -14.   0.   0. -13. -12. -11.   0.]]
